### ISSUE TITLE
not install Dedicated Server

### ISSUE THREAD

**Issue by nordron01** [xLorey/FluxLoader#20]
OS windows 10 
Steam Project Zomboid Dedicated Server

PS D:\SteamLibrary\steamapps\common\Project Zomboid Dedicated Server> java -jar .\FluxLoader-0.7.1.jar --install
##################################################
#                                                #
#                   FluxLoader                   #
#                     v0.7.1                     #
#                                                #
#    https://github.com/xLorey/FluxLoader-PZ     #
#         https://discord.gg/BwSuTdEGJ4          #
#                                                #
##################################################

<13/01/2024 13:06:27> [FluxLoader]: Preparing for installation FluxLoader...
<13/01/2024 13:06:27> [FluxLoader]: Checking the installer location...
Exception in thread "main" java.lang.Exception: There is no game folder 'zombie' next to FluxLoader.
 Please place this 'jar' file in the correct location!

        at io.xlorey.FluxLoader.Installer.checkGameFolder(Installer.java:29)
        at io.xlorey.FluxLoader.Installer.install(Installer.java:48)
        at io.xlorey.FluxLoader.Main.main(Main.java:26)
PS D:\SteamLibrary\steamapps\common\Project Zomboid Dedicated Server>

**Comment by Deknil** [comment]
Hello. To do this, the loader must be placed next to the `zombie` folder.  For servers, the path should look something like this: `D:\SteamLibrary\steamapps\common\Project Zomboid Dedicated Server\java\`

![image](https://github.com/xLorey/FluxLoader/assets/147500212/fb4ba371-fe69-4c69-946c-f8aaff26fd5f)

**Comment by nordron01** [comment]
Thank you very much

**Comment by nordron01** [comment]
Install Directoro to 
D:\SteamLibrary\steamapps\common\Project Zomboid Dedicated Server\java\
